project:
  type: website
  output-dir : "docs"
website:
  title: "Global Health Epidemiologist"
  navbar:
    left :
      - text : "Home"
        file : index.qmd
      - text : "Portfolio"
        file : portfolio.qmd
      - text : "CV"
        file : cv.qmd
    right:
      - about me
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linked-in
        href: https://linkedin.com/
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

